### ISSUE TITLE
Load enviroment variables in config

### ISSUE THREAD

**Issue by checor** [instruct-br/nameko-reloader#10]
Hello! Thanks for the great tool!

I've tried to replace the use of nameko_reloader, instead of nameko cli, to reload my scripts.

However, when I have a config.yml like this, with environment variables, will not work:

```
# config.yml
AMQP_URI: pyamqp://${RABBITMQ_USER:guest}:${RABBITMQ_PASSWORD:password}@${RABBITMQ_HOST:localhost}
```

An error like this would be throwed:
```
[...]
File "/usr/lib/python3.8/urllib/parse.py", line 174, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as 'localhost}:${RABBIT_PORT:5672}'
```

The nameko [cli](https://github.com/nameko/nameko/blob/master/nameko/cli/main.py#L16) uses [regex](https://nameko.readthedocs.io/en/stable/cli.html#environment-variable-substitution) to substitute environment variables. Is there a way this can be supported?

Thanks!

**Comment by arthurzeras** [comment]
The error was related to yaml parse, this [PR](https://github.com/instruct-br/nameko-reloader/pull/12) updates the method from `unsafe_load` to `safe_load` and change the related nameko version to `2.14`.

Thanks for the report.
